local Private = select(2, ...)
local AddOn = Private.AddOn

function AddOn:OnInitialize()
    Private.DB = LibStub("AceDB-3.0"):New("UnhaltedUIDB", Private:GetDefaults(), true)
end

function AddOn:OnEnable()
    if not C_AddOns.IsAddOnLoaded("ElvUI") then return Private:PrettyPrint("Requires |cFF1784D1ElvUI|r, please install it and reload.") end
    Private:CreateGUI()
    Private:SetupAutoDelete()
    Private:SetupAutoQuest()
    Private:SetupAutoSellGreys()
    Private:SetupAutoSignUp()
    Private:SetupBigWigsSkin()
    Private:SetupBloodlustAlert()
    Private:SetupBugSack()
    Private:SetupCVars()
    Private:SetupCombatAlert()
    Private:SetupCombatTimer()
    Private:SetupDamageMeter()
    Private:SetupDungeonCasts()
    Private:UpdateBlizzardEnhancements()
    Private:SetupLootRollFix()
    Private:UpdateCastbarInterruptCooldown()
    Private:UpdateOverAbsorbs()
    Private:SetupGatewayUsableReminder()
    Private:SetupInnervateAlert()
    Private:SetupKeystoneRerollReminder()
    Private:SetupLSToasts()
    Private:SetupMissingPersonalBuffs()
    Private:SetupMissingRaidBuffs()
    Private:SetupMouseCursor()
    Private:SetupPositionRaidWarningFrame()
    Private:SetupPowerInfusionAlert()
    Private:SetupRemoveBossBanner()
    Private:SetupRemoveLossOfControlFrame()
    Private:SetupRemoveTalkingHead()
    Private:SetupSkipCinematics()
    Private:SetupTargetedSpells()
    Private:SetupTimeSpiralAlert()
    Private:SetupVendorHelper()
end
