local Private = select(2, ...)
local LSM = Private.LSM

LSM:Register("statusbar", "|cFF6080FFUnhalted|rUI: Half Bar", "Interface\\AddOns\\ElvUI_Unhalted\\Media\\StatusBars\\Half_Bar.tga")

LSM:Register("sound", "|cFF6080FFUnhalted|r: 1", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\1.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: 2", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\2.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: 3", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\3.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: 4", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\4.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: 5", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\5.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: 6", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\6.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: 7", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\7.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: 8", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\8.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: 9", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\9.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: 10", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\10.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: First", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\First.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Second", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Second.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Third", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Third.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Fourth", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Fourth.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Fifth", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Fifth.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Sixth", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Sixth.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Seventh", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Seventh.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Eight", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Eight.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Ninth", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Ninth.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Tenth", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Tenth.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Move In", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\MoveIn.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Move Out", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\MoveOut.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Move Left", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\MoveLeft.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Move Right", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\MoveRight.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Jump", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Jump.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Dodge", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Dodge.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Run", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Run.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Interrupt", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Interrupt.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Stun", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Stun.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Defensive", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Defensive.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Personal", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Personal.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: PI", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\PI.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Phase 1", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Phase1.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Phase 2", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Phase2.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Phase 3", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Phase3.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Intermission", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Intermission.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Collect Orbs", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\CollectOrbs.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Orbs", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Orbs.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Add", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Add.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Adds", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Adds.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: CC", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\CC.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Feast", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Feast.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Repair", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Repair.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Healthstones", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Healthstones.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Help Summon", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\HelpSummon.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Collect", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Collect.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Drop Off", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\DropOff.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Drop", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Drop.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Refresh", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Refresh.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Stack", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Stack.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Soak", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Soak.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Up", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Up.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Down", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Down.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Left", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Left.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Right", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Right.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Back", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Back.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Front", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Front.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Skull", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Skull.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: White", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\White.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Square", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Square.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Blue", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Blue.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Orange", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Orange.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Circle", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Circle.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Star", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Star.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Yellow", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Yellow.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Triangle", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Triangle.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Green", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Green.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Silver", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Silver.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Moon", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Moon.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Charge", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Charge.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Feet", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Feet.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Watch Feet", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Watch Feet.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: High Energy", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\High Energy.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Low Energy", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Low Energy.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Swap", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Swap.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Switch", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Switch.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Stop Casting", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\StopCasting.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Stop", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Stop.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Soon", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Soon.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Wave", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Wave.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Winds", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Winds.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Totem", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Totem.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Beam", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Beam.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Buff", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Buff.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Clear", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Clear.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Close", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Close.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Come Up", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Come Up.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Go Down", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Go Down.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Dispel", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Dispel.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Group Up", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Group Up.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Cauldron", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Cauldron.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Incorporeal", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Incorporeal.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Your Turn", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\YourTurn.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Afflicted", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Afflicted.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Knock", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Knock.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Knock Back", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\KnockBack.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Knock Up", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\KnockUp.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Queue", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Queue.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Ring", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Ring.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Gate", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Gate.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Hide", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Hide.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Focus", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Focus.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: CC Adds", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\CCAdds.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Spawn", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Spawn.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Spawning", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Spawning.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Spawning Adds", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\SpawningAdds.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Pick Up", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\PickUp.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Far", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Far.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Near", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Near.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Far Spawn", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\FarSpawn.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Near Spawn", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\NearSpawn.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Shroomling", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Shroomling.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Fungling", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Fungling.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Vines", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Vines.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Souls", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Souls.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Mind Control", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\MindControl.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: MC", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\MC.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Fear", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Fear.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Feared", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Feared.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Incoming", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Incoming.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Potion", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Potion.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Fixate", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Fixate.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Stare", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Stare.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Look at Add", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\LookatAdd.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Find Add", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\FindAdd.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Fixated", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Fixated.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Face Away", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\FaceAway.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Face Towards", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\FaceTowards.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Axe", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Axe.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Miasma", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Miasma.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Time Spiral", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\TimeSpiral.mp3]])

LSM:Register("sound", "|cFF6080FFUnhalted|r: Acoustic Guitar", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\AcousticGuitar.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Air Horn", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\AirHorn.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Applause", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Applause.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Banana Peel Slip", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\BananaPeelSlip.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Batman Punch", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\BatmanPunch.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Bike Horn", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\BikeHorn.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Blast", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Blast.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Bleat", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Bleat.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Boxing Arena Sound", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\BoxingArenaSound.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Brass", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Brass.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Cartoon Voice Baritone", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\CartoonVoiceBaritone.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Cartoon Walking", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\CartoonWalking.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Cat Meow 2", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\CatMeow2.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Chicken Alarm", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\ChickenAlarm.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Circle", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Circle.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Cow Mooing", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\CowMooing.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Double Whoosh", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\DoubleWhoosh.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Drums", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Drums.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Error Beep", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\ErrorBeep.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Glass", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Glass.mp3]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Goat Bleating", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\GoatBleating.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Heartbeat Single", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\HeartbeatSingle.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Kitten Meow", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\KittenMeow.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Oh No", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\OhNo.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Portal", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Portal.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Ringing Phone", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\RingingPhone.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Roaring Lion", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\RoaringLion.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Robot Blip", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\RobotBlip.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Rooster Chicken Calls", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\RoosterChickenCalls.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Run Away", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\RunAway.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Sharp Punch", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\SharpPunch.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Sheep Bleat", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\SheepBleat.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Shotgun", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Shotgun.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Squeaky Toy Short", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\SqueakyToyShort.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Squish Fart", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\SquishFart.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Synth Chord", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\SynthChord.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Tada Fanfare", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\TadaFanfare.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Temple Bell Huge", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\TempleBellHuge.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Torch", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Torch.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Warning Siren", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\WarningSiren.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Water Drop", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\WaterDrop.ogg]])
LSM:Register("sound", "|cFF6080FFUnhalted|r: Xylophone", [[Interface\AddOns\ElvUI_Unhalted\Media\Sounds\Xylophone.ogg]])
